### ISSUE TITLE
[BUG] Cannot read properties of null (reading 'frontmatter')

### ISSUE THREAD

**Issue by the1gofer** [danielo515/obsidian-modal-form#189]
**Describe the bug**
I believe the error may have been introduced in the update today.   The `result.asFrontmatterString() `function seems to have stopped working.  and I get the following error.

```
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'frontmatter')
    at isFmDisable (plugin:auto-note-mover:1806:68)
    at fileCheck (plugin:auto-note-mover:2079:13)
    at eval (plugin:auto-note-mover:2125:66)
    at e.tryTrigger (app.js:1:712355)
    at e.trigger (app.js:1:712288)
    at t.trigger (app.js:1:729920)
    at t.onChange (app.js:1:720164)
    at e.trigger (app.js:1:542391)
    at e.<anonymous> (app.js:1:540463)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at app.js:1:236279
    at new Promise (<anonymous>)
    at v (app.js:1:236024)
    at e.reconcileFileCreation (app.js:1:539940)
    at e.<anonymous> (app.js:1:539581)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at a (app.js:1:236081)
plugin:templater-obsidian:61 Templater Error: Template parsing error, aborting. 
 result.asFrontmatterString is not a function
```

**To Reproduce**
```
<%*
const modalForm = app.plugins.plugins.modalforms.api;
const result = modalForm.openForm('case');

let frontmatter = result.asFrontmatterString();
-%>
---
fileClass: Case
<% frontmatter %>
case: <% result.get('case name') %>

```

**Expected behavior**
write the content of the form to a string in the YAML format. 

**Additional context**
This same code seemed to have been working for me last night, and when I went to work on the templates today, I was getting the error.   

Modal forms Version: 1.34.0
Obsidian Version: 1.5.3

**Comment by the1gofer** [comment]
my error

**Comment by danielo515** [comment]
So not an error at the end? You can use one of the shortcuts (asYaml for
example) if that is easier to type
